dist: trusty
sudo: false
language: ruby
addons:
  apt:
    packages:
      - fontforge
      - woff-tools
deploy:
  - provider: script
    script: ci/gh-pages.sh
    skip_cleanup: true
    on:
      branch: master
